---
- name: MySQL Server Setup
  hosts: dbsrvgrp
  become: yes
  become_method: sudo
  tasks:

      - name: Create MySQL database Test123 and table
        mysql_query:
          login_user: root
          login_password: {{ mysql_root_password }}
          query: |
            CREATE DATABASE IF NOT EXISTS Test123 CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
            USE Test123;
            CREATE TABLE login (
                id INT(11) NOT NULL AUTO_INCREMENT,
                name VARCHAR(100) NOT NULL,
                email VARCHAR(100) NOT NULL,
                password VARCHAR(120) NOT NULL,
                PRIMARY KEY (id)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
