
- name: Setup Apache2 & Deploy Artifact
  hosts: stagingsrvgrp
  become: yes
  vars:
    timestamp: "{{ansible_date_time.date}}_{{ansible_date_time.hour}}_{{ansible_date_time.minute}}"
  tasks:
    
    - name: Download latest weblab.tgz from nexus
      get_url:
        url: "http://{{USER}}:{{PASS}}@{{nexusip}}:8081/repository/{{reponame}}/{{artifactname}}/{{hyphen}}/{{registers_version}}"
        dest: "/tmp/registersapp-{{registers_version}}"
      register: tgzdeploy
      tags:
       - deploy

    - stat:
        path: /var/www/{{ http_host }}/public_html
      register: artifact_stat
      tags:
        - deploy

    - name: Stop Apache
      service:
        name: "{{item}}"
        state: stopped
      loop:
        - apache2
        - php8.1-fpm
      tags:
        - deploy

    - name: Try Backup and Deploy
      block:
      - name: Archive public_html dir with timestamp
        archive:
          path: /var/www/{{ http_host }}/public_html
          dest: "/opt/public_html_{{timestamp}}.tgz"
        when: artifact_stat.stat.exists
        register: archive_info
        tags:
          - deploy

      - name: copy public_html dir with BK name
        shell: cp -r public_html BK
        args:
          chdir: /var/www/{{ http_host }}/

      - name: Delete current artifact
        file:
          path: "{{item}}"
          state: absent
        when: archive_info.changed
        loop:
          - /var/www/{{ http_host }}/public_html
          - /var/www/{{ http_host }}/public_html.tgz
        tags:
          - deploy

      - name: Try deploy artifact else restore from previos BK
        block:
         - name: Deploy weblab artifact
           copy:
             src: "/tmp/registersapp-{{registers_version}}"
             dest: /var/www/{{ http_host }}/public_html.tgz
             remote_src: yes
           register: deploy_info
           tags:
            - deploy
        rescue:
          - shell: cp -r BK public_html
            args:
              chdir: /var/www/{{ http_host }}/

      rescue:
       - name: Start Apache2 php8.1-fpm
         service:
           name: "{{item}}" 
           state: started
         loop:
           - apache2
           - php8.1-fpm

    - name: Start Apache2 php8.1-fpm
      service:
        name: "{{item}}"		  
        state: started
      when: deploy_info.changed
      loop:
        - apache2
        - php8.1-fpm
      tags:
        - deploy

    - name: Extract public_html.tgz
      unarchive:
        src: /var/www/{{ http_host }}/public_html.tgz
        dest: /var/www/{{ http_host }}
        remote_src: yes

    - name: Creat new directory public_html
      file:
        path: /var/www/{{ http_host }}/public_html
        state: directory

    - name: change directory and install dependencies
      command: chdir=/var/www/{{ http_host }}/package npm install --force

    - name: Run Build
      command: chdir=/var/www/{{ http_host }}/package npm run build

    - name: Copy all file of Build to public_html
      shell: mv /var/www/{{ http_host }}/package/build/* /var/www/{{ http_host }}/public_html	  

    - name: Delete dir package
      command: rm -rf /var/www/{{ http_host }}/package          

  handlers:
   - name: Restart Apache2
     service:
      name: Apache2
      state: restarted
