
- name: Setup Apache2 & Deploy Artifact
  hosts: stagingsrvgrp
  become: yes
  vars:
    timestamp: "{{ansible_date_time.date}}_{{ansible_date_time.hour}}_{{ansible_date_time.minute}}"
  tasks:

    - name: Update timezone
      command: ln -f -s /usr/share/zoneinfo/Asia/Ho_Chi_Minh /etc/localtime
          
    - name: Download latest weblab.tgz from nexus
      get_url:
        url: "http://{{USER}}:{{PASS}}@{{nexusip}}:8081/repository/{{reponame}}/{{artifactname}}/{{hyphen}}/{{weblab_version}}"
        dest: "/tmp/weblabapp-{{weblab_version}}"
      register: tgzdeploy
      tags:
       - deploy

    - stat:
        path: /var/www/weblab.local/public_html
      register: artifact_stat
      tags:
        - deploy

    - name: Stop Nginx
      service:
        name: "{{item}}"
        state: stopped
      loop:
        - nginx
        - php8.1-fpm
      tags:
        - deploy

    - name: Try Backup and Deploy
      block:
      - name: Archive public_html dir with timestamp
        archive:
          path: /var/www/weblab.local/public_html
          dest: "/opt/public_html_{{timestamp}}.tgz"
        when: artifact_stat.stat.exists
        register: archive_info
        tags:
          - deploy

      - name: copy public_html dir with BK name
        shell: cp -r public_html BK
        args:
          chdir: /var/www/weblab.local/

      - name: Delete current artifact
        file:
          path: "{{item}}"
          state: absent
        when: archive_info.changed
        loop:
          - /var/www/weblab.local/public_html
          - /var/www/weblab.local/public_html.tgz
        tags:
          - deploy

      - name: Try deploy artifact else restore from previos BK
        block:
         - name: Deploy weblab artifact
           copy:
             src: "/tmp/weblabapp-{{weblab_version}}"
             dest: /var/www/weblab.local/public_html.tgz
             remote_src: yes
           register: deploy_info
           tags:
            - deploy
        rescue:
          - shell: cp -r BK public_html
            args:
              chdir: /var/www/weblab.local/

      rescue:
       - name: Start Nginx php8.1-fpm
         service:
           name: "{{item}}" 
           state: started
         loop:
           - nginx
           - php8.1-fpm

    - name: Start Nginx php8.1-fpm
      service:
        name: "{{item}}"		  
        state: started
      when: deploy_info.changed
      loop:
        - nginx
        - php8.1-fpm
      tags:
        - deploy
      notify: Reload Nginx

    - name: Extract public_html.tgz
      unarchive:
        src: /var/www/weblab.local/public_html.tgz
        dest: /var/www/weblab.local
        remote_src: yes

    - name: Creat new directory public_html
      file:
        path: /var/www/weblab.local/public_html
        state: directory

    - name: Install curl
      apt:
        name: curl
        state: present

    - name: Download and run Node.js setup script
      shell: curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash -

    - name: Install Nodejs
      apt:
        name: nodejs
        state: present

    - name: change directory and install dependencies
      command: chdir=/var/www/weblab.local/package npm install --force

    - name: Run Build
      command: chdir=/var/www/weblab.local/package npm run build

    - name: Copy all file of Build to public_html
      shell: mv /var/www/weblab.local/package/build/* /var/www/weblab.local/public_html	  

    - name: Delete dir package
      command: rm -rf /var/www/weblab.local/package               

  handlers:
   - name: Reload Nginx
     service:
      name: nginx
      state: reloaded
