
- name: Setup Nginx & Deploy Artifact
  hosts: stagingsrvgrp
  become: yes
  become_method: sudo
  vars:
    timestamp: "{{ansible_date_time.date}}_{{ansible_date_time.hour}}_{{ansible_date_time.minute}}"
  tasks:
         
    - name: Download latest weblab.tgz from nexus
      get_url:
        #url: "http://{{USER}}:{{PASS}}@{{nexus_ip}}:8081/repository/{{reponame}}/{{artifactname}}/{{hyphen}}/{{registers_version}}"
        url: "http://{{nexus_ip}}:8081/repository/{{reponame}}/{{artifactname}}/{{hyphen}}/{{registers_version}}"        
        dest: "/tmp/registersapp-{{registers_version}}"
        url_username: "{{USER}}"
        url_password: "{{PASS}}"
        force_basic_auth: yes
      register: tgzdeploy
      tags:
       - deploy

    - stat:
        path: /var/www/{{ http_host }}/public_html
      register: artifact_stat
      tags:
        - deploy

    - name: Stop Nginx
      service:
        name: "{{item}}"
        state: stopped
      loop:
        - nginx
        - php8.1-fpm
      tags:
        - deploy

    - name: Try Backup and Deploy
      block:
      - name: Archive public_html dir with timestamp
        archive:
          path: /var/www/{{ http_host }}/public_html
          dest: "/opt/public_html_{{timestamp}}.tgz"
        when: artifact_stat.stat.exists
        register: archive_info
        tags:
          - deploy

      - name: copy public_html dir with BK name
        shell: cp -r public_html BK
        args:
          chdir: /var/www/{{ http_host }}/

      - name: Delete current artifact
        file:
          path: "{{item}}"
          state: absent
        when: archive_info.changed
        loop:
          - /var/www/{{ http_host }}/public_html
          - /var/www/{{ http_host }}/public_html.tgz
        tags:
          - deploy

      - name: Try deploy artifact else restore from previos BK
        block:
         - name: Deploy weblab artifact
           copy:
             src: "/tmp/registersapp-{{registers_version}}"
             dest: /var/www/{{ http_host }}/public_html.tgz
             remote_src: yes
           register: deploy_info
           tags:
            - deploy
        rescue:
          - shell: cp -r BK public_html
            args:
              chdir: /var/www/{{ http_host }}/

      rescue:
       - name: Start Nginx php8.1-fpm
         service:
           name: "{{item}}" 
           state: started
         loop:
           - nginx
           - php8.1-fpm

    - name: Start Nginx php8.1-fpm
      service:
        name: "{{item}}"		  
        state: started
      when: deploy_info.changed
      loop:
        - nginx
        - php8.1-fpm
      tags:
        - deploy
      notify: Reload Nginx

    - name: Extract public_html.tgz
      unarchive:
        src: /var/www/{{ http_host }}/public_html.tgz
        dest: /var/www/{{ http_host }}
        remote_src: yes

    - name: Creat new directory public_html
      file:
        path: /var/www/{{ http_host }}/public_html
        state: directory

    - name: Install curl
      apt:
        name: curl
        state: present

    - name: Download and run Node.js setup script
      shell: curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash -

    - name: Install Nodejs
      apt:
        name: nodejs
        state: present

    - name: change directory and install dependencies
      command: chdir=/var/www/{{ http_host }}/package/client npm install

    - name: Run Build
      command: chdir=/var/www/{{ http_host }}/package/client npm run build

    - name: Copy all file of Build to public_html
      shell: mv /var/www/{{ http_host }}/package/client/build/* /var/www/{{ http_host }}/public_html

    - name: Copy backend, folder server
      shell: mv /var/www/{{ http_host }}/package/server /var/www/{{ http_host }}/public_html	  

    - name: Delete dir package
      command: rm -rf /var/www/{{ http_host }}/package

    - name: Delete Node_modules Server
      command: rm -rf /var/www/{{ http_host }}/public_html/server/node_modules

    - name: change directory and install dependencies Server
      command: chdir=/var/www/{{ http_host }}/public_html/server npm install       

    - name: Install PM2
      npm:
        name: pm2
        global: yes
        state: present

    - name: Start Backend server.js
      command: chdir=/var/www/{{ http_host }}/public_html/server pm2 start server.js

    - name: Add start PM2 crontab when reboot
      lineinfile:
        dest: /etc/crontab
        line: "@reboot root sh -c 'cd /var/www/{{ http_host }}/public_html/server && pm2 start server.js'"
        insertafter: EOF
      notify: Restart Cron           

  handlers:
   - name: Reload Nginx
     service:
      name: nginx
      state: reloaded
      
   - name: Restart Cron
     service:
      name: cron
      state: restarted      
    
